### ISSUE TITLE
Cell.Empty does not behave as expected

### ISSUE THREAD

**Issue by jeffsherman0** [norbert-radyk/spoiwo#10]
I would expect that empty cells have their cell type set to 
org.apache.poi.ss.usermodel.Cell.CELL_TYPE_BLANK

But this does not seem to be the case so I end up doing something like this: 
        import com.norbitltd.spoiwo.natures.xlsx.Model2XlsxConversions._

```
    //wb is a spoiwo workbook 
    val rawPoiWorkbook = wb.convertAsXlsx()

        rawPoiWorkbook.foreach(sheet =>
            sheet.foreach(row =>
                row.foreach(cell =>
                    if (cell != null && 
                        cell.getCellType == org.apache.poi.ss.usermodel.Cell.CELL_TYPE_STRING &&
                        cell.getStringCellValue == "")
                        cell.setCellType(org.apache.poi.ss.usermodel.Cell.CELL_TYPE_BLANK)
                )
            )
        )
```

**Comment by nightscape** [comment]
I'm just running into the same issue. Sometimes it's important to distinguish between an empty String and a null, especially with the new "overwriting" feature where neither an empty String nor just leaving that cell out might be the correct thing to do.

Would it be ok to make `Cell.Empty` return a `BlankCell` instance with an additional match in `Model2XlsxConversions` like this
```scala
case BlankCell(_, _, _)       => cell.setCellValue(null) // This makes POI write a blank cell
```

I could create a corresponding PR.
