### ISSUE TITLE
DateUtil.isCellDateFormatted(xlsx) is false

### ISSUE THREAD

**Issue by intracer** [norbert-radyk/spoiwo#13]
No default date style format is applied to xlsx cells from the models, so DateUtil.isCellDateFormatted(xlsx) cannot detect that cell is in date format

    val model = Cell(new LocalDate(2011, 11, 13).toDate)
    val xlsx = convert(model)

    assert(DateUtil.isCellDateFormatted(xlsx))  // fails

**Comment by norbert-radyk** [comment]
Fixed  as a part of 1.1.1 release (just pushed to maven central, can take 1-2 days to be publicly available).
