### ISSUE TITLE
next release - 1.0.7?

### ISSUE THREAD

**Issue by lielran** [norbert-radyk/spoiwo#21]
Hi , 

any estimation when will be next release?(v1.0.7)
i would like to use the password protection feature(not in 1.0.6)

**Comment by norbert-radyk** [comment]
Hi Liel,

We are planning 1.1.0 within the next week, it will not only password
protection features, but also upgrades to latest POI and support for Java 8.

Hope that helps and thank you for using Spoiwo.

Kindest regards,
Norbert

**Comment by lielran** [comment]
Thanks. can please upload a snapshot meanwhile?

**Comment by norbert-radyk** [comment]
The new release is now available on Maven Central: http://mvnrepository.com/artifact/com.norbitltd/spoiwo_2.11/1.1.0
