### ISSUE TITLE
Warnings rg.openxmlformats.schemas.spreadsheetml.x2006.main.*

### ISSUE THREAD

**Issue by andeliero92** [norbert-radyk/spoiwo#22]
Warning:scalac: Class org.openxmlformats.schemas.spreadsheetml.x2006.main.CTSortState not found - continuing with a stub.
    Warning:scalac: Class org.openxmlformats.schemas.spreadsheetml.x2006.main.CTExtensionList not found - continuing with a stub.
    Warning:scalac: Class org.openxmlformats.schemas.spreadsheetml.x2006.main.STTableType not found - continuing with a stub.

What does it means? how can i avoid these messages?

**Comment by bardurdam** [comment]
You can tell the compiler to ignore those warnings, or you can add the following library dependency to your project:
```
"org.apache.poi" % "ooxml-schemas" % "1.3"
```
The reason for the warnings, is that only a subset of those ooxml schemas (called poi-ooxml-schemas) comes as a transient dependency via the Apache POI dependency that spoiwo depends on.

The Apache POI documentation states as follows:

> poi-ooxml requires poi-ooxml-schemas. This is a substantially smaller version of the ooxml-schemas jar (ooxml-schemas-1.3.jar for POI 3.14 or later, ooxml-schemas-1.1.jar for POI 3.7 up to POI 3.13, ooxml-schemas-1.0.jar for POI 3.5 and 3.6). The larger ooxml-schemas jar is normally only required for development.
