### ISSUE TITLE
Write-Only?

### ISSUE THREAD

**Issue by dliulabs** [norbert-radyk/spoiwo#24]
I could not find a single mention of read from Excel file in the project document, nor from the samples. All use cases of spoiwo are for write-only. Is this project only able to create Excel files but not able to read from it?

**Comment by yairogen** [comment]
@biztalk my question exactly. did you find anything that can read the files too?

**Comment by TimFoerster** [comment]
Its on the roadmap for version 1.3.
[source](https://raw.githubusercontent.com/norbert-radyk/spoiwo/master/documents/SPOIWO.pdf) Slide 18

**Comment by norbert-radyk** [comment]
I was on the roadmap at some point, however realistically I would not expect it to be implemented anytime soon, unless someone decides to take an initiative on this one - it's an open source project in the end ;) At the moment spoiwo has only spreadsheet generation capabilities.

**Comment by juhoimmonen** [comment]
Have there been any updates to reading functionality?

**Comment by norbert-radyk** [comment]
Sadly not. Implementation of that capability would require a significant effort which would add only a slight benefit over what's currently offered by Apache POI.
