### ISSUE TITLE
HTML support?

### ISSUE THREAD

**Issue by amuradyan** [norbert-radyk/spoiwo#32]
Hi.

I read in the docs that spoiwo provides spreadsheet HTML representation but I cant "find it"
Can you provide an example?

Thanks a lot!

**Comment by norbert-radyk** [comment]
Hi @amuradyan,

I am afraid the documents are out of date with regards to that feature as it has been removed with:
https://github.com/norbert-radyk/spoiwo/commit/0e4452556236f74e7980b26aa259e2e80b111822#diff-046989ec8b468fed3627e5862afc919c

Supporting internal model conversion to HTML was an idea in the past, However the concept has been removed as it would add a lot of maintenance burden for relatively little value. Therefore to obtain html for your spreadsheets you can either generate the CSV and use one of the many libraries which support CSV -> HTML conversions, or choose to save them as web pages in Excel (after generating the spreadsheet) should you care about all the styling/colurs etc. 

There are no plans to add this feature back to Spoiwo at current time.

**Comment by norbert-radyk** [comment]
Documentation updated to remove references for HTML conversions.

**Comment by amuradyan** [comment]
Thanks
