### ISSUE TITLE
Missing support for HyperLinkUrl when using withCellValues()

### ISSUE THREAD

**Issue by lglossman** [norbert-radyk/spoiwo#34]
Pattern matching is not exhaustive when calling Row.withCellValues and throws a exception when passed an `HyperLinkUrl` type: `java.lang.UnsupportedOperationException: Unable to construct cell from class com.norbitltd.spoiwo.model.HyperLinkUrl type value!`

**Comment by norbert-radyk** [comment]
Issue addressed and release performed today, should be available in Maven Central in the next 24h
