### ISSUE TITLE
add autoSizeColumn support

### ISSUE THREAD

**Issue by tg44** [norbert-radyk/spoiwo#56]
There is a super function on the HSSFSheet: 
http://poi.apache.org/apidocs/dev/org/apache/poi/hssf/usermodel/HSSFSheet.html#autoSizeColumn-int-

Would be nice to add this to the sheet.

My current workaround if sb interested:
```
    import collection.JavaConverters._
    Future {
      val output = new ByteArrayOutputStream()
      val cols   = grid.width
      val wb = Sheet(name = sheetName)
        .withGrid(grid)
        .convertAsXlsx
      wb.sheetIterator.asScala
        .foreach(s => (0 to cols).foreach(i => s.autoSizeColumn(i, true)))
      wb.write(output)
      output.toByteArray
    }
```

**Comment by norbert-radyk** [comment]
Have you tried the following approach?

`
      val columns = (0 to grid.width).map(i => Column(index = i, autoSized = true))
      Sheet(name = sheetName)
        .withGrid(grid)
        .withColumns(columns.toList)
        .saveAsXlsx("test.xlsx")
`

**Comment by tg44** [comment]
Wow, probably this is what I missed... Will try tomorrow and close this if working!

**Comment by tg44** [comment]
Sorry for the late reply! Works as expected, thx the info!
