### ISSUE TITLE
When protecting Worksheet, how to specify the actions allowed?

### ISSUE THREAD

**Issue by alain-espina** [norbert-radyk/spoiwo#59]
Is there a way to specify which actions are allowed in Excel when protecting it with a password? I can locked the cells but then I want to allow the user to perform other things like when you protect the worksheet in Excel, you can specify which ones are allowed.

![image](https://user-images.githubusercontent.com/51341762/82721381-a7a13000-9c8a-11ea-9b9c-cd1ff5b9377c.png)

**Comment by norbert-radyk** [comment]
This functionality was indeed missing from spoiwo, so I have added it now in the 1.8.0 version of the library (I expect it to be available from the distribution servers in the next 24h). 

Also added a small example of how you'd use this functionality: https://github.com/norbert-radyk/spoiwo/blob/master/examples/src/main/scala/com/norbitltd/spoiwo/examples/features/LockingExample.scala

Hope that helps :)
